-- Artifacts: photographs of things Joe made, marked, or owned.
--
-- A column on `photos` rather than a second table. An artifact photograph is a
-- photograph in every respect that matters to the code — same Cloudflare Images
-- id, same moderation, same archive job, same lightbox — and the only thing that
-- differs is which gallery it lands on. A parallel table would have duplicated
-- all of that to express one boolean.
--
-- Everything already submitted is a photograph of Joe or his life, so defaulting
-- to 'photo' is correct for the existing rows; anything miscategorised gets moved
-- by hand on the admin page.
alter table photos add column if not exists kind text not null default 'photo'
  check (kind in ('photo', 'artifact'));

-- Both galleries filter on kind, so it leads the index. The old photos_gallery
-- index can't serve these queries — it has no kind column, so each page would
-- scan every approved row and re-sort.
create index if not exists photos_gallery_by_kind
  on photos (kind, sort_order nulls last, created_at)
  where status = 'approved';


-- Submissions that aren't photographs: a recording, a scan, a document, source
-- code, a letter in his block-print hand.
--
-- Deliberately NOT in `photos`. These have no Cloudflare Images id and no
-- viewable derivative, so every gallery query and the archive job would need to
-- learn to skip them — and the day one slipped through, a gallery would try to
-- render an audio file as an <img>. Separate table, no such failure available.
--
-- Nothing here is ever served publicly. The file goes to R2, the admin page
-- lists it and can download it, and how (or whether) to present each one is
-- decided by hand afterwards, the way the recipes were.
create table if not exists artifact_files (
  id           uuid primary key default gen_random_uuid(),
  submitter    text,
  email        text,                                  -- optional, private
  description  text,                                  -- what it is, from the sender
  filename     text not null,                         -- as supplied; display only, never a path
  content_type text,                                  -- as claimed by the browser; not trusted
  byte_size    bigint,
  storage_key  text not null unique,                  -- R2 key, generated by us
  status       text not null default 'pending'
               check (status in ('pending', 'approved', 'rejected')),
  ip_hash      text,
  created_at   timestamptz not null default now(),
  reviewed_at  timestamptz
);

create index if not exists artifact_files_queue
  on artifact_files (created_at)
  where status = 'pending';
